import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthContextProvider } from "../context/AuthContext";
import { CartProvider } from "../context/CartContext";
import { WishlistProvider } from "../context/WishlistContext";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import WhatsAppButton from "../components/WhatsAppButton";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`} suppressHydrationWarning>
        <AuthContextProvider>
          <CartProvider>
            <WishlistProvider>
              <div className="print:hidden">
                <Navbar />
              </div>
              <main className="flex-grow">
                {children}
              </main>
              <div className="print:hidden">
                <WhatsAppButton />
                <Footer />
              </div>
            </WishlistProvider>
          </CartProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
